# Generated by Django 2.0 on 2018-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('short_url', models.CharField(max_length=100)),
                ('text_message', models.CharField(max_length=2000)),
                ('click_count', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
